config/routes.rb
Videostreamer::Application.routes.draw do
  resources :videos
  resources :ratings, only: :update
  devise_for :users
  get "landing/index"

  root :to => "videos#index"

  match "/panda/authorize_upload", :to => "panda#authorize_upload", :via => [:get, :post]
  match "/panda/authorize_upload_postprocess", :to => "panda#authorize_upload_postprocess", :via => [:get, :post]
  match "/videos/postprocess", :to => "videos#postprocess", :via => [:get, :post]

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :video

  validate :ensure_not_creator

  def ensure_not_creator
    errors.add :user_id, "is the creator of the video" if video.user_id == user_id
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :ratings
	has_many :videos

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ActiveRecord::Base
	has_many :ratings
	belongs_to :user
  validates_presence_of :panda_video_id

  def self.order_by_ratings

  end

  def panda_video
    @panda_video ||= Panda::Video.find(panda_video_id)
  end

  def average_rating
  	if ratings.size == 0
  		return 0
  	else
  		return ratings.sum(:score) / ratings.size
  	end
  end

  def user_rating(user)
    rating = Rating.where(video_id: self.id, user_id: user.id).first
    unless rating
      rating = Rating.create(video_id: self.id, user_id: user.id, score: 0)
    end
    rating
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/panda_controller.rb
class PandaController < ApplicationController
  def verify_authenticity_token
    handle_unverified_request unless (form_authenticity_token == upload_payload['csrf'])
  end

  def upload_payload
    @upload_payload ||= JSON.parse(params['payload'])
  end

  def authorize_upload
    # ACCEPTABLE_CONTENT_TYPES = ['video/x-flv', 'video/mp4',
    #   'application/x-mpegURL', 'video/MP2T', 'video/3gpp',
    #   'video/quicktime', 'video/x-msvideo', 'video/x-ms-wmv']
    # payload = JSON.parse(params['upload_payload'])
    # unless ACCEPTABLE_CONTENT_TYPES.include?(payload['content_type'])
    #   redirect_to videos_url, alert: "That file format is not accepted!"
    # else
    upload = Panda.post('/videos/upload.json', {
      file_name: upload_payload['filename'],
      file_size: upload_payload['filesize'],
      profiles: "h264"
    })

    render :json => {:upload_url => upload['location']}
    # end
  end

  # added from Rails example
  def authorize_upload_postprocess

    upload = Panda.post('/videos/upload.json', {
      file_name: upload_payload['filename'],
      file_size: upload_payload['filesize'],
      profiles: "h264",
    })

    render :json => {:upload_url => upload['location'], :postprocess_url => "/videos/postprocess"}
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

	def update
		@rating = Rating.find(params[:id])
		@video = @rating.video
		if @rating.update_attributes(score: params[:score])
			respond_to do |format|
				format.js
			end
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :xml, :xls, :json, :js
  # overrides built in devise users_controller

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  # enables admin to change another user's subscription plans and
  # update Stripe customer account, which will apply refunds, charges needed
  def update                    # for changing user's role
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])        # , :as => :admin)
      @user.update_role(role) unless role.nil?
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alsert => "Unable to update user."
    end
  end

  def destroy                   # only admins can destroy users
    user = User.find(params[:id])
    unless user == current_user   # ensure admin can't delete himself
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  include Rails.application.routes.url_helpers
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all.sort {|a, b| b.average_rating <=> a.average_rating}
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])
    @original_video = @video.panda_video
    @h264_encoding = @original_video.encodings["h264"]
    @rating = Rating.where(video_id: @video.id, user_id: current_user.id).first
    unless @rating
      @rating = Rating.create(video_id: @video.id, user_id: current_user.id, score: 0)
    end
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # added from Rails example
  def postprocess
    video_params = JSON.parse(params["upload_response"])
    @video = Video.new(:panda_video_id => video_params["id"], :title => "Title-to-be-edited-later")

    if @video.save
      render :json => {:play_url => url_for(@video), :id => @video_id}
    end
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.create!(video_params)
    @video.user_id = current_user.id
    # may be necessary instead of below: redirect_to :action => :show, :id => @video.id
    redirect_to :action => :index
#    respond_to do |format|
#      if @video.save
#        format.html { redirect_to @video, notice: 'Video was successfully created.' }
#        format.json { render action: 'show', status: :created, location: @video }
#      else
#        format.html { render action: 'new' }
#        format.json { render json: @video.errors, status: :unprocessable_entity }
#      end
#    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @original_video = @video.panda_video
    @original_video.delete
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :panda_video_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
	def gravatar_for(email, options = { size: 50 })
		gravatar_id = Digest::MD5::hexdigest(email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
		image_tag(gravatar_url, alt: email, class: "gravatar")
	end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/landing/index.html.haml
%h1 Landing#index
%p Find me in app/views/landing/index.html.haml

app/views/layouts/_body.html.haml
/ main container
= render 'layouts/todo'
/ = link_to "Home", root_path
/ = render 'shared/notifications'
/ = yield
/ = render 'layouts/footer'

app/views/layouts/_footer.html.haml
.footer
  %p &copy; Lev Brie 2013

app/views/layouts/_head.html.haml
%head
  %title= "Videostreamer"
  = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
  = javascript_include_tag "application", "data-turbolinks-track" => true
  %script{:type => "text/javascript", :src  => "//cdn.pandastream.com/u/2.0/panda-uploader.min.js"}
  = csrf_meta_tags

app/views/layouts/_todo.html.haml
%section.hbox.stretch
  / .aside
  %aside#nav.bg-primary.aside-sm
    %section.vbox
      %header.dker.nav-bar.nav-bar-fixed-top
        %a.btn.btn-link.visible-xs{"data-target" => "#nav", "data-toggle" => "class:nav-off-screen"}
          %i.icon-reorder
        %a.nav-brand{"data-toggle" => "fullscreen", href: "#"} VideoStreamer
        %a.btn.btn-link.visible-xs{"data-target" => ".nav-user", "data-toggle" => "class:show"}
          %i.icon-comment-alt
      %section
        / user
        .bg-success.nav-user.hidden-xs.pos-rlt
          .nav-avatar.pos-rlt
            %a.thumb-sm.avatar.animated.rollIn{"data-toggle" => "dropdown", href: "#"}
              = gravatar_for current_user.email if current_user
              / %img{alt: "", src: "images/avatar.jpg"}/
              %span.caret.caret-white
            %ul.dropdown-menu.m-t-sm.animated.fadeInLeft
              %span.arrow.top
              %li
                %a{href: "#"} Settings
              %li
                %a{href: "#{edit_user_password_path}"} Profile
              %li
                %a{href: "#"}
                  %span.badge.bg-danger.pull-right 3
                  Notifications
              %li.divider
              %li
                %a{href: "#"} Help
              %li
                = link_to "Sign out", destroy_user_session_path, :method => :delete
            .visible-xs.m-t.m-b
              %a.h3{href: "#"} lev.brie@gmail.com
              %p
                %i.icon-map-marker
                London, UK
        / / user
        / nav
        %nav.nav-primary.hidden-xs
          %ul.nav
            %li.active
              %a{href: "#{videos_path}"}
                %i.icon-eye-open
                %span Videos
            %li
              %a{href: "#{new_user_session_path}"}
                %i.icon-pencil
                %span Log In
        / / nav
        / note
        .bg-danger.wrapper.hidden-vertical.animated.fadeInUp.text-sm
          %a.pull-right.m-r-n-sm.m-t-n-sm{"data-dismiss" => "alert", href: "#"}
            %i.icon-close.icon-remove
          Hi, welcome to videostreamer, a scalable video cloud built on AWS.
        / / note
      %footer.footer.bg-gradient.hidden-xs
        %a.btn.btn-sm.btn-link.m-r-n-xs.pull-right{"data-toggle" => "ajaxModal", href: "modal.lockme.html"}
          %i.icon-off
        %a.btn.btn-sm.btn-link.m-l-n-sm{"data-toggle" => "class:nav-vertical", href: "#nav"}
          %i.icon-reorder
  / /.aside
  / .vbox
  %section#content
    %section.vbox
      %header.header.bg-white.b-b
        = link_to "Welcome to Video Streamer!", videos_path
        .row
          .col-lg-12
            %section.panel
              = render 'shared/notifications'
              = yield
              = render 'layouts/footer'
    %a.hide.nav-off-screen-block{"data-target" => "#nav", "data-toggle" => "class:nav-off-screen", href: "#"}
  / /.vbox

app/views/layouts/_top.html.haml
!!!
%html
  = render 'layouts/head'
  %body#videostreamer_app{class: "#{controller_name} #{action_name}"}

app/views/layouts/application.html.haml
= render 'layouts/top'
#application_layout
  = render 'layouts/header'
  = render 'layouts/body'

app/views/ratings/update.js.erb
$("#star_" + <%= @video.id %>).raty({
  readOnly: true,
  score: <%= @video.average_rating %>,
  path: '/'
});

$("#user_star_" + <%= @video.id %>).raty({
  score: <%= @rating.score %>,
  path: '/',
  click: function(score, evt) {
    $.ajax({
      url: '/ratings/' + <%= @rating.id %>,
      type: 'PATCH',
      data: { score: score }
    }).done(function (data){});
  }
});

app/views/shared/_notifications.html.haml
/
  Adds contents of the special flash variable to site layout for messages
  that appear and then disappear on subsequent reloads
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} x
    = msg

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = f.text_field :email
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/index.html.haml
#pad-wrapper.object-wrapper
  .row-fluid.header
    %h3 Users
  / Users table
  .row-fluid.table
    %table.table.table-hover
      %thead
        %tr
          %th.span4.sortable
            Name
          %th.span2.sortable
            %span.line>
            Created On
          %th.span2.sortable
            %span.line>
            Role
          %th.span2.sortable.align-right
            %span.line>
            Email
      %tbody
        - @users.each.with_index do |user, index|
          / row
          <tr #{"class=first" if index == 0}>
          %td
            = gravatar_for user.email
            = link_to "#{user.email}", user, :class => "email"
          %td
            = user.created_at.to_date
          %td.align-right
            = link_to user.email, user
          %td
            = render user
            = link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/videos/_form.html.erb
<div class='span4'>
  <%= form_for @video do |f| %>
    <fieldset>
      <legend>Upload a new video</legend>

      <label>Title</label>

      <input type="text" name='video[title]' placeholder="Give a title">

      <span class="help-block">Upload will start immediately after select</span>

      <br/>

      <input type="hidden" name="video[panda_video_id]" id="panda_video_id" />

<!--       <div class='progress progress-striped progress-success active'>
        <span id="progress-bar" class='bar'></span>
      </div> -->
      <div id="progress-bar" class="progress progress-sm progress-striped  active">
        <div class="progress-bar progress-bar-success" data-toggle="tooltip" data-original-title="30%" style="width: 30%"></div>
      </div>

      <div class='btn-toolbar'>
        <div id='browse-files' class='btn btn-primary btn-success'><span>Choose file</span></div>
        <button id='cancel-button' class='btn btn-danger'>Cancel</button>
      </div>

      <div class="well well-large" id="drop-file">
        Drop files here
      </div>

    </fieldset>

  <% end %>
</div>

<script>

$('#cancel-button').click(function(e){
  uploader.cancel(uploader.getQueuedFiles()[0]);
  e.preventDefault();
})

var uploader = panda.uploader.init({
  'buttonId': 'browse-files',
  'fileDropId': 'drop-file',
  'progressBarId': 'progress-bar',
  'onQueue': function(files) {
    $.each(files, function(i, file) {
      uploader.setPayload(file, {'csrf': "<%= form_authenticity_token %>"});
    })
  },
  'onSuccess': function(file, data) {
    $("#panda_video_id").val(data.id)
  },
  'onComplete': function(){
    if($("#panda_video_id").val())
      $("#new_video").submit();
  },
  'onError': function(file, message) {
    alert(message);
  },
  'onCancel': function(file) {
    uploader.setProgress(0);
  }
});

</script>

app/views/videos/_video.html.erb
<% original = video.panda_video %>
<% encoding = original.encodings['h264'] %>
<div class="col-lg-6">
  <div class="col-lg-12">
    <h3>Title: <%= video.title %></h3>
    <p>Upload Timestamp: <%= video.created_at %></p>
    <%= link_to "S3 Url: #{encoding.url}", encoding.url %>
<!--       <p>Here's the raw video information</p> -->
    <section>
      <h4>Video Input: </h4>
      <pre><%= h original.inspect %></pre>
    </section>

<!--       <section>
      <h4>Video Output H264:</h4>
      <pre><%= h encoding.inspect %></pre>
    </section> -->
  </div>

  <% if encoding.success? %>
    <!-- HTML5 player -->
    <video class="col-lg-12" id="video_<%= video.id %>" width="auto" height="auto" preload="none"
      poster="<%= encoding.screenshots.first %>" controls>
      <source src="<%= encoding.url %>" type="video/mp4">
    </video>
    Average Rating: <div id="star_<%= video.id %>"></div>
    User Rating: <div id="user_star_<%= video.id %>"></div>
    <%= link_to 'Delete', video_path(video.id), method: :delete, data: {confirm: "Are you sure?"}, class: "italic" %>
    <!-- <h3>Thumbnails</h3> -->
    <!-- <ul class="thumbnails"> -->
    <%# encoding.screenshots.each do |src| %>
<!--           <li class="span3">
        <a class="thumbnail" href="#">
          <img src="<%#= src %>"
               style="width: auto; height: auto">
        </a>
      </li> -->
    <%# end %>
    </ul>
  <% else %>
    <div class='progress progress-striped progress-success'>
      <span id="progress-bar" class='bar' style="width: <%= encoding.encoding_progress.to_i %>%"><%= encoding.encoding_progress %> %</span>
    </div>
    The video is still processing, refresh the page in a few seconds.
  <% end %>
</div>

<script>
  $("#star_" + <%= video.id %>).raty({
    readOnly: true,
    score: <%= video.average_rating %>,
    path: ''
  });

  $('#user_star_' + <%= video.id %>).raty({
    score: <%= video.user_rating(current_user).score %>,
    path: '',
    click: function(score, evt) {
      $.ajax({
        url: '/ratings/' + <%= video.user_rating(current_user).id %>,
        type: 'PATCH',
        data: { score: score }
      });
    }
  });
</script>

app/views/videos/destroy.js.erb
$("#video_<%= @video.id %>").remove();

app/views/videos/edit.html.haml
%h1 Editing video

= render 'form'

= link_to 'Show', @video
\|
= link_to 'Back', videos_path

app/views/videos/index.html.erb
<div class="col-lg-12">
  <!-- .crousel fade -->
  <section class="panel bg-dark">
    <div class="carousel slide carousel-fade panel-body" id="c-fade">
        <ol class="carousel-indicators out">
          <li data-target="#c-fade" data-slide-to="0" class="active"></li>
          <li data-target="#c-fade" data-slide-to="1" class=""></li>
        </ol>
        <div class="carousel-inner">
          <div class="item active">
            <p class="text-center">
              <em class="h4 text-mute">Upload a Video Now!</em><br>
              <%= link_to "Upload Video", new_video_path, class: "btn btn-sm btn-info" %>
            </p>
          </div>
          <div class="item">
            <p class="text-center">
              <em class="h4 text-mute">And Rate them right then and there!</em><br>
              <small class="text-muted">Only one rating per person</small>
            </p>
          </div>
        </div>
        <a class="left carousel-control" href="#c-fade" data-slide="prev">
          <i class="icon-angle-left"></i>
        </a>
        <a class="right carousel-control" href="#c-fade" data-slide="next">
          <i class="icon-angle-right"></i>
        </a>
    </div>
  </section>
  <!-- / .carousel fade -->
</div>
<div class="row">
	<div class="col-lg-12">
	  <!-- .accordion -->
	  <div class="panel-group m-b" id="accordion2">
	    <div class="panel">
	      <div class="panel-heading">
	        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
	          Watch Me On A Live Stream Now! (Click to hide this video)
	        </a>
	      </div>
	      <div id="collapseOne" class="panel-collapse">
					<div class="panel-body text-sm">
						<div class="col-lg-6 col-lg-offset-3">
							<object width="530" height="309"> <param name="movie" value="http://fpdownload.adobe.com/strobe/FlashMediaPlayback_101.swf"></param><param name="flashvars" value="src=http%3A%2F%2Fdqd7r0low23oz.cloudfront.net%2Fhds-live%2Flivepkgr%2F_definst_%2Fliveevent%2Flivestream-ldb2001.f4m"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://fpdownload.adobe.com/strobe/FlashMediaPlayback_101.swf" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="530" height="309" flashvars="src=http%3A%2F%2Fdqd7r0low23oz.cloudfront.net%2Fhds-live%2Flivepkgr%2F_definst_%2Fliveevent%2Flivestream-ldb2001.f4m"></embed></object>
						</div>
	        </div>
	      </div>
	    </div>
	  </div>
	</div>
</div>
<h2>Listing All Other Videos</h2>
<div class="row">
  <%= render @videos %>
</div>

app/views/videos/index.html.haml
%h1 Listing videos

%table
  %tr
    %th Url
    %th Name
    %th
    %th
    %th

  - @videos.each do |video|
    %tr
      %td= video.url
      %td= video.name
      %td= link_to 'Show', video
      %td= link_to 'Edit', edit_video_path(video)
      %td= link_to 'Destroy', video, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Video', new_video_path

app/views/videos/new.html.haml
%h1 New video

= render 'form'

= link_to 'Back', videos_path

app/views/videos/old_form.html.haml
/ = form_for @video do |f|
/   - if @video.errors.any?
/     #error_explanation
/       %h2= "#{pluralize(@video.errors.count, "error")} prohibited this video from being saved:"
/       %ul
/         - @video.errors.full_messages.each do |msg|
/           %li= msg
/
/   .field
/     = f.label :url
/     = f.text_field :url
/   .field
/     = f.label :name
/     = f.text_field :name
/   .actions
/     = f.submit 'Save'
/ = form_for @video do |f|
/   / field where the video ID will be stored after the upload
/   %input{name: "video[panda_video_id]", type: "hidden", id: "panda_video_id"}/
/   %label Title
/   %input{name: "video[title]", placeholder: "Give a title", type: "text"}/
/   / upload progress bar (optional)
/   .progress
/     %span#progress-bar.bar
/   / file selector
/   #browse Choose file
/ :javascript
/   var upl = panda.uploader.init({
/     'buttonId': 'browse',
/     'progressBarId': 'progress-bar',
/     'onQueue': function(files) {
/       $.each(files, function(i, file) {
/         upl.setPayload(file, {'csrf': "#{form_authenticity_token}"});
/       })
/     },
/     'onSuccess': function(file, data) {
/       $("#panda_video_id").val(data.id)
/     },
/     'onComplete': function(){
/       $("#new_video").submit();
/     }
/   });


.span8
  %fieldset
    %legend Upload a new video
    %div
      .row-fluid
        .span10 Select a video file on your computer
        .span2
          #browse-files.btn.btn-primary.btn-success
            %span Choose file
    %table#upload-table.table.table-striped
      %thead
        %tr
          %th Name
          %th
          %th
          %th
  %button#btn-upload.btn{type: "button"} Upload

:javascript
  UploadTable = function(uploader) {
    this.uploader = uploader;
    this.holder_ = $("#upload-table");
  }

  UploadTable.prototype.add = function(file){
    var fileRow = new UploadFileRow(uploader, file);

    var dom = fileRow.draw()
    dom.attr('id', "upload-"+file.id)

    this.holder_.append(dom);

    fileRow.attachEvents()
  }

  UploadTable.prototype.remove = function(file){
    this.holder_.find("#upload-"+file.id).remove();
  }

  UploadFileRow = function(uploader, file) {
    this.uploader_ = uploader
    this.file_ = file
  }

  UploadFileRow.prototype.draw = function(){
    var self = this;

    this.html = $("<tr>")
          .append($("<td>", {'class': 'td-filename'}).html(this.file_.name))
          .append($("<td>", {'class': 'td-progress'})
            .append($("<div>", {'class': 'progress'})
              .append($("<div>", {'class': 'bar', 'id': "progress-" + this.file_.id}))))
          .append($("<td>", {'class': 'td-filesize'}).html(this.file_.size))
          .append($("<td>", {'class': 'td-action'})
            .append($("<button>", {'type': 'button', 'class': 'btn btn-danger btn-cancel'}).text('Cancel')))

    return this.html;
  }

  UploadFileRow.prototype.attachEvents = function(){
    var self = this;

    $(this.file_)
      .on("start", function(event, progress){
        self.html.find('.progress')
          .addClass('progress-striped active');
      })
      .on("progress", function(event, progress){
        self.html.find('.progress .bar')
          .css({"width": progress + '%'})
          .text(progress + "%");
      })
      .on("error", function(event, message){
        self.html.find('.progress')
          .addClass('progress-danger')
          .removeClass('active')
          .find('.bar')
            .css({"width": '100%'})

        alert(message);

      })
      .on("success", function(event, data){
        self.html.find('.progress')
          .addClass('progress-success')
          .removeClass('active')
          .find('.bar')
            .css({"width": '100%'})

        self.html.find(".td-action")
                  .html($("<a>", {
                    'type': 'button',
                    'class': 'btn btn-info',
                    'target': "_blank",
                    'href': data["play_url"]}).text('Play'))
      })

    this.html.find(".btn-cancel").click(function(e){
      self.uploader_.cancel(self.file_);
      e.preventDefault();
    })
  }

  $("#btn-upload").click(function(e){
    uploader.setEnabled(false);
    uploader.start()
    e.preventDefault();
  })

  var uploader = panda.uploader.init({
    'buttonId': 'browse-files',
    'authorizeUrl': '/panda/authorize_upload_postprocess',
    'autoStart': false,
    'allowSelectMultipleFiles': true,
    'onQueue': function(files) {
      $.each(files, function(i, file) {
        uploadTable.add(this);
        uploader.setPayload(file, {'csrf': "<%= form_authenticity_token %>"});
      })
    },
    'onStart': function(file, percent){
      $(file).trigger('start');
    },
    'onProgress': function(file, percent) {
      $(file).trigger("progress", percent)
    },
    'onSuccess': function(file, data) {
      $(file).trigger('success', data);
    },
    'onComplete': function(file, data) {
      uploader.setEnabled(true);
    },
    'onError': function(file, data) {
      $(file).trigger('error', data);
    },
    'onCancel': function(file) {
      uploadTable.remove(file)
    },
    'onPause': function(file) {
      console.log('on paused', file);
    }
  });

  var uploadTable = new UploadTable(uploader);

app/views/videos/old_show.html.haml
%p#notice= notice

%h2= @video.title
%p= h @video.panda_video.inspect
%p
  %b Title:
  = @video.title

= link_to 'Edit', edit_video_path(@video)
\|
= link_to 'Back', videos_path

app/views/videos/show.html.erb
<h2><%= @video.title %></h2>
<p>Average Rating:</p>
<div id="star"></div>
<p>Your Rating:</p>
<div id="user_star"></div>

<p>Here's the raw video information:</p>

<div class='span8'>

<section>
  <h4>Video Input: </h4>
  <pre><%= h @original_video.inspect %></pre>
</section>

<section>
  <h4>Video Output H264:</h4>
  <pre><%= h @h264_encoding.inspect %></pre>
</section>

<% if @h264_encoding.success? %>

  <h3>HTML5 Player</h3>

  <!-- HTML5 player -->
  <video id="movie" width="<%= @h264_encoding.width %>" height="<%= @h264_encoding.height %>" preload="none"
    poster="<%= @h264_encoding.screenshots.first %>" controls>
    <source src="<%= @h264_encoding.url %>" type="video/mp4">
  </video>

  <h3>Thumbnails</h3>

  <ul class="thumbnails">
  <% @h264_encoding.screenshots.each do |src| %>
    <li class="span3">
      <a class="thumbnail" href="#">
        <img src="<%= src %>"
             style="width: <%= @h264_encoding.width %>; height: <%= @h264_encoding.height %>">
      </a>
    </li>
  <% end %>
  </ul>

<% else %>

  <div class='progress progress-striped progress-success'>
    <span id="progress-bar" class='bar' style="width: <%= @h264_encoding.encoding_progress.to_i %>%"><%= @h264_encoding.encoding_progress %> %</span>
  </div>

  The video is still processing, refresh the page in a few seconds.
<% end %>

</div>

<script>
  $('#star').raty({
    readOnly: true,
    score: <%= @video.average_rating %>,
    path: '/assets'
  });

  $('#user_star').raty({
    score: <%= @rating.score %>,
    path: '/assets',
    click: function(score, evt) {
      $.ajax({
        url: '/ratings/' + <%= @rating.id %>,
        type: 'PATCH',
        data: { score: score }
      });
    }
  });
</script>